name: Deploy Main

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: pnpm/action-setup@v4
    
      - run: pnpm install 
      - run: pnpm run build

      - name: Copy resources
        run: |
          cp -r css build/
          cp -r images build/
          cp -r misc build/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: deploy
          target-folder: deploy/main
          folder: build
